# Generated by Django 5.0.2 on 2024-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompaniya_app', '0005_alter_staff_staff_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo_images/')),
            ],
        ),
    ]
