# Generated by Django 5.0.2 on 2024-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompaniya_app', '0007_alter_staff_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='logo',
            name='LOGO_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/'),
        ),
    ]
