# Generated by Django 5.0.2 on 2024-05-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kompaniya_app', '0008_remove_logo_logo_image_logo_logo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='LOGO_IMAGE',
            new_name='logo_image',
        ),
    ]
