# Generated by Django 5.0.2 on 2024-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompaniya_app', '0011_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
